#!/usr/bin/env bash
set -euo pipefail

# Refreshes the game assemblies CI builds and tests against: copies of the real
# ones, or with --mock, copies whose method bodies all throw. Run it on a machine
# with the game installed, after every game update. See docs/ci.md.

usage() {
    cat <<'EOF'
Usage: tools/game-refs/refresh.sh --refs <clone of the private refs repository> [--label <game version>] [--mock] [--verify]

Copies every game assembly the projects reference into
<refs>/Cities2_Data/Managed, so CI builds and tests against the game's real code.
That is the game's code: keep the repository private. Reads the game from
$CS2_GAME_PATH, or the Steam path Directory.Build.props defaults to.

  --label    the game version, recorded in the manifest (for example 1.3.6f1)
  --mock     write mock copies instead: all types and signatures, every method
             body replaced by a throw, so the repository holds none of the game's
             code; tests tagged Requires=Game cannot pass against them
  --verify   then build and test this repository against them, as CI does
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd -P)"
REFASMER_VERSION="2.0.3"
DOTNET_BIN="${DOTNET:-dotnet}"

refs=""
label=""
mock=false
verify=false

while [ $# -gt 0 ]; do
    case "$1" in
        --refs) refs="${2:?--refs needs a path}"; shift 2 ;;
        --label) label="${2:?--label needs a value}"; shift 2 ;;
        --mock) mock=true; shift ;;
        --verify) verify=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

[ -n "$refs" ] || { usage >&2; exit 1; }
command -v "$DOTNET_BIN" >/dev/null 2>&1 || { echo "ERROR: dotnet not found" >&2; exit 1; }

game="${CS2_GAME_PATH:-$HOME/.local/share/Steam/steamapps/common/Cities Skylines II}"
managed="$game/Cities2_Data/Managed"
[ -d "$managed" ] || { echo "ERROR: no game assemblies at $managed; set CS2_GAME_PATH" >&2; exit 1; }

parent="$(cd "$(dirname "$refs")" 2>/dev/null && pwd -P)" || { echo "ERROR: no such directory: $(dirname "$refs")" >&2; exit 1; }
refs="$parent/$(basename "$refs")"

# Checked before anything is written. These are the game's assemblies, or with
# --mock its API surface, and this repository is public.
case "$refs/" in
    "$REPO_ROOT/"*)
        echo "ERROR: refusing to write inside this repository: $refs" >&2
        exit 1
        ;;
esac

mkdir -p "$refs"

sha256() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}

# Whatever the projects reference, so the list cannot drift from them.
assemblies=()
while IFS= read -r name; do
    assemblies+=("$name")
done < <(grep -hoE 'CS2ManagedPath\)/[A-Za-z0-9_.]+\.dll' \
    "$REPO_ROOT"/BetterBuildingMenu/*.csproj "$REPO_ROOT"/BetterBuildingMenu.Tests/*.csproj \
    | sed 's|.*)/||' | sort -u)

[ "${#assemblies[@]}" -gt 0 ] || { echo "ERROR: found no game references in the projects" >&2; exit 1; }

if $mock; then
    tools="$(mktemp -d)"
    trap 'rm -rf "$tools"' EXIT
    "$DOTNET_BIN" tool install --tool-path "$tools" JetBrains.Refasmer.CliTool --version "$REFASMER_VERSION" >/dev/null
fi

out="$refs/Cities2_Data/Managed"
rm -rf "$out"
mkdir -p "$out"

manifest="$refs/MANIFEST.md"
{
    if $mock; then
        echo "# Mock Cities: Skylines II assemblies"
        echo
        echo "Generated by \`tools/game-refs/refresh.sh --mock\` in Better Building Menu, for its CI."
        echo "Every method body is a throw: none of the game's code is here. Keep this repository private."
        echo
        echo "- Game version: ${label:-not recorded}"
        echo "- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "- Tool: JetBrains.Refasmer.CliTool $REFASMER_VERSION, \`--all --mock\`, then \`tools/game-refs/FixNativeMethods.cs\`"
    else
        echo "# Cities: Skylines II assemblies"
        echo
        echo "Copied by \`tools/game-refs/refresh.sh\` in Better Building Menu, for its CI."
        echo "These are the game's own assemblies, unmodified: its code. Keep this repository private,"
        echo "and never publish them, as a workflow artifact or otherwise."
        echo
        echo "- Game version: ${label:-not recorded}"
        echo "- Copied: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    fi
    echo
    echo "| Assembly | SHA-256 of the game's copy |"
    echo "|---|---|"
} > "$manifest"

for name in "${assemblies[@]}"; do
    source="$managed/$name"
    [ -f "$source" ] || { echo "ERROR: missing from the game install: $source" >&2; exit 1; }

    if $mock; then
        # --all keeps private struct fields, which the compiler reads for the
        # unmanaged constraint ECS code uses. --mock, unlike a reference assembly,
        # loads at run time, so tests can use the types; a call throws.
        "$tools/refasmer" -q --all --mock -O "$out" "$source"
        [ -f "$out/$name" ] || { echo "ERROR: Refasmer wrote no $name" >&2; exit 1; }
    else
        cp "$source" "$out/$name"
    fi

    echo "| $name | $(sha256 "$source") |" >> "$manifest"
done

if $mock; then
    # Refasmer gives the runtime's own methods a body too, and the runtime then refuses
    # to load their types: every UnityEngine.Object, so every prefab, and every delegate.
    "$DOTNET_BIN" run "$SCRIPT_DIR/FixNativeMethods.cs" -- "$out" >/dev/null
    echo "Wrote ${#assemblies[@]} mock assemblies to $out"
else
    echo "Copied ${#assemblies[@]} game assemblies to $out"
fi

if $verify; then
    echo "=== Building and testing against them, as CI does ==="
    # From clean and with CI=true, as CI builds: an incremental build prints no
    # warnings for what it does not recompile, and CI fails on any warning.
    rm -rf "$REPO_ROOT"/BetterBuildingMenu/obj "$REPO_ROOT"/BetterBuildingMenu/bin \
        "$REPO_ROOT"/BetterBuildingMenu.Tests/obj "$REPO_ROOT"/BetterBuildingMenu.Tests/bin
    CI=true CS2_GAME_PATH="$refs" "$REPO_ROOT/build.sh" backend
    if $mock; then
        # A test that fails here and passes against the real game calls into it;
        # tag it [Trait("Requires", "Game")]. See docs/ci.md.
        CI=true CS2_GAME_PATH="$refs" CS2_TEST_FILTER="Requires!=Game" "$REPO_ROOT/build.sh" test
    else
        CI=true CS2_GAME_PATH="$refs" "$REPO_ROOT/build.sh" test
    fi
fi

echo
echo "Next, review the change and publish it:"
echo "  git -C \"$refs\" add -A && git -C \"$refs\" commit -m \"CS2 ${label:-<version>}\" && git -C \"$refs\" push"
