#!/usr/bin/env bash
set -euo pipefail

# Regenerates the mock game assemblies CI builds and tests against. Run it on a
# machine with the game installed, after every game update. See docs/ci.md.

usage() {
    cat <<'EOF'
Usage: tools/game-refs/refresh.sh --refs <clone of the private refs repository> [--label <game version>] [--verify]

Writes mock copies of every game assembly the projects reference into
<refs>/Cities2_Data/Managed: all types and signatures, every method body
replaced by a throw, so the private repository holds none of the game's code.
Reads the game from $CS2_GAME_PATH, or the Steam path Directory.Build.props
defaults to.

  --label    the game version, recorded in the manifest (for example 1.3.6f1)
  --verify   then build and test this repository against the mocks, as CI does
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd -P)"
REFASMER_VERSION="2.0.3"
DOTNET_BIN="${DOTNET:-dotnet}"

refs=""
label=""
verify=false

while [ $# -gt 0 ]; do
    case "$1" in
        --refs) refs="${2:?--refs needs a path}"; shift 2 ;;
        --label) label="${2:?--label needs a value}"; shift 2 ;;
        --verify) verify=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

[ -n "$refs" ] || { usage >&2; exit 1; }
command -v "$DOTNET_BIN" >/dev/null 2>&1 || { echo "ERROR: dotnet not found" >&2; exit 1; }

game="${CS2_GAME_PATH:-$HOME/.local/share/Steam/steamapps/common/Cities Skylines II}"
managed="$game/Cities2_Data/Managed"
[ -d "$managed" ] || { echo "ERROR: no game assemblies at $managed; set CS2_GAME_PATH" >&2; exit 1; }

parent="$(cd "$(dirname "$refs")" 2>/dev/null && pwd -P)" || { echo "ERROR: no such directory: $(dirname "$refs")" >&2; exit 1; }
refs="$parent/$(basename "$refs")"

# Checked before anything is written. The mocks are the game's API surface,
# and this repository is public.
case "$refs/" in
    "$REPO_ROOT/"*)
        echo "ERROR: refusing to write inside this repository: $refs" >&2
        exit 1
        ;;
esac

mkdir -p "$refs"

sha256() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}

# Whatever the projects reference, so the list cannot drift from them.
assemblies=()
while IFS= read -r name; do
    assemblies+=("$name")
done < <(grep -hoE 'CS2ManagedPath\)/[A-Za-z0-9_.]+\.dll' \
    "$REPO_ROOT"/BetterBuildingMenu/*.csproj "$REPO_ROOT"/BetterBuildingMenu.Tests/*.csproj \
    | sed 's|.*)/||' | sort -u)

[ "${#assemblies[@]}" -gt 0 ] || { echo "ERROR: found no game references in the projects" >&2; exit 1; }

tools="$(mktemp -d)"
trap 'rm -rf "$tools"' EXIT
"$DOTNET_BIN" tool install --tool-path "$tools" JetBrains.Refasmer.CliTool --version "$REFASMER_VERSION" >/dev/null

out="$refs/Cities2_Data/Managed"
rm -rf "$out"
mkdir -p "$out"

manifest="$refs/MANIFEST.md"
{
    echo "# Mock Cities: Skylines II assemblies"
    echo
    echo "Generated by \`tools/game-refs/refresh.sh\` in Better Building Menu, for its CI."
    echo "Every method body is a throw: none of the game's code is here. Keep this repository private."
    echo
    echo "- Game version: ${label:-not recorded}"
    echo "- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "- Tool: JetBrains.Refasmer.CliTool $REFASMER_VERSION, \`--all --mock\`, then \`tools/game-refs/FixNativeMethods.cs\`"
    echo
    echo "| Assembly | SHA-256 of the game's copy |"
    echo "|---|---|"
} > "$manifest"

for name in "${assemblies[@]}"; do
    source="$managed/$name"
    [ -f "$source" ] || { echo "ERROR: missing from the game install: $source" >&2; exit 1; }

    # --all keeps private struct fields, which the compiler reads for the
    # unmanaged constraint ECS code uses. --mock, unlike a reference assembly,
    # loads at run time, so tests can use the types; a call throws.
    "$tools/refasmer" -q --all --mock -O "$out" "$source"
    [ -f "$out/$name" ] || { echo "ERROR: Refasmer wrote no $name" >&2; exit 1; }

    echo "| $name | $(sha256 "$source") |" >> "$manifest"
done

# Refasmer gives the runtime's own methods a body too, and the runtime then refuses
# to load their types: every UnityEngine.Object, so every prefab, and every delegate.
"$DOTNET_BIN" run "$SCRIPT_DIR/FixNativeMethods.cs" -- "$out" >/dev/null

echo "Wrote ${#assemblies[@]} mock assemblies to $out"

if $verify; then
    echo "=== Building and testing against the mocks, as CI does ==="
    CS2_GAME_PATH="$refs" "$REPO_ROOT/build.sh" backend
    # A test that fails here and passes against the real game calls into it;
    # tag it [Trait("Requires", "Game")]. See docs/ci.md.
    CS2_GAME_PATH="$refs" CS2_TEST_FILTER="Requires!=Game" "$REPO_ROOT/build.sh" test
fi

echo
echo "Next, review the change and publish it:"
echo "  git -C \"$refs\" add -A && git -C \"$refs\" commit -m \"CS2 ${label:-<version>}\" && git -C \"$refs\" push"
